title = "LoneStar's wiki"
baseURL = 'https://wangjailei.xyz/'
languageCode = 'zh-cn'
theme = ["hugo-blog-awesome", "reveal-hugo"]
defaultContentLanguage = "zh-cn"
googleAnalytics = '' # G-MEASUREMENT_ID
enableEmoji = true

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
    # codeFences = false
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]] 
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef="categories"
    name = 'Categories'
    url = '/categories/'
    weight = 30
  [[menu.main]]
    pageRef="tags"
    name = 'Tags'
    url = '/tags/'
    weight = 40
  [[menu.main]]
    pageRef="notes"
    name = 'Notes'
    url = '/notes/'
    weight = 50

[params]
  sitename = "LoneStar's wiki"
  defaultColor = "light" # set default color mode: dark or light
  description = "personal wiki"
  goToTop = true

[params.author]
  avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "LoneStar's wiki"
  name = "LoneStar"
  description = ""

[[params.socialIcons]]
name = "github"
url = "https://github.com/wlonestar"

[[params.socialIcons]]
name = "bilibili"
url = "https://space.bilibili.com/433694656"

[[params.socialIcons]]
name = "Rss"
url = "index.xml"

[tableOfContents]
startLevel = 2 # ToC starts from H2
endLevel = 4 # ToC ends at H4
ordered = false # generates <ul> instead of <ol>

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
custom_theme = "stylesheets/custom.scss"
custom_theme_compile = true
highlight_theme = "github"
slide_number = "c/t"
history = true
