title = "LoneStar's wiki"
baseURL = 'https://wangjailei.xyz/'
languageCode = 'zh-cn'
theme = ["hugo-blog-awesome", "reveal-hugo"]
defaultContentLanguage = "zh-cn"
# To enable Google Analytics 4 (gtag.js) provide G-MEASUREMENT_ID below.
# To disable  Google Analytics, simply leave the field empty or remove the next line
googleAnalytics = '' # G-MEASUREMENT_ID
# Enable emojis globally
enableEmoji = true

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
    codeFences = false
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]] 
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef="categories"
    name = 'Categories'
    url = '/categories/'
    weight = 30
  [[menu.main]]
    pageRef="tags"
    name = 'Tags'
    url = '/tags/'
    weight = 20
  # [[menu.main]]
  #   pageRef="about"
  #   name = 'About'
  #   url = '/about/'
  #   weight = 40

[params]
  sitename = "LoneStar's wiki"
  defaultColor = "light" # set default color mode: dark or light
  description = "personal wiki"

[params.author]
  avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "LoneStar's wiki"
  name = "LoneStar"
  description = ""

# [[params.socialIcons]]
# name = "github"
# url = "https://github.com/wlonestar"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
custom_theme = "stylesheets/custom.scss"
custom_theme_compile = true
highlight_theme = "github"
slide_number = "c/t"
history = true
